# This assumes OverOps as Influx is bundled with OverOps Server 
# and Grafana is proxied behind the OverOps UI (e.g. https://app.overops.com/grafana)
apiVersion: 1

datasources:
- name: OO
  type: influxdb
  access: proxy
  database: telegraf
  is_default: true
  url: ${TAKIPI_API_URL}/api/v1/oo-as-influx
