apiVersion: 1

datasources:
- name: OO
  type: influxdb
  access: proxy
  database: telegraf
  is_default: true
  #url: http://localhost:8186 # assuming OverOps-as-influx standalone
  url: ${TAKIPI_API_URL}/api/v1/oo-as-influx # assuming OverOps Server 
